/// Flutter icons Ischooler
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ischooler
///      fonts:
///       - asset: fonts/Ischooler.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class IschoolerIcons {
  IschoolerIcons._();

  static const _kFontFam = 'Ischooler';
  static const String? _kFontPkg = null;

  static const IconData teacher_7 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
